version: '3'

services:
  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=marmitaDev
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
  test_db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=marmitaTest
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
  web:
    build: .
    command: adonis serve --dev
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - db
      - test_db
